server.port=8081

app.os-places.endpoint=https://api.os.uk/search/places/v1/postcode
app.os-places.api-key=19TsD7WrhvugWKD2wcJRGCsmQuAdN6wg

app.epc.endpoint=https://epc.opendatacommunities.org/api/v1/domestic/search
app.epc.api-key=ccafd32af9810db82be7d6f41fe69b876ac06b2e
app.epc.username=alfie-brash@live.co.uk

app.cors.allowed-origins=http://localhost:8080
