server.port=${PORT:8081}

app.os-places.endpoint=https://api.os.uk/search/places/v1/postcode
app.os-places.api-key=${APP_OS_PLACES_API_KEY:}

app.epc.endpoint=https://epc.opendatacommunities.org/api/v1/domestic/search
app.epc.api-key=${APP_EPC_API_KEY:}
app.epc.username=${APP_EPC_USERNAME:}

app.flood-monitoring.endpoint=https://environment.data.gov.uk/flood-monitoring/id/floods
app.flood-monitoring.search-radius-km=${APP_FLOOD_SEARCH_RADIUS_KM:5}

app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:8080}